### PR TITLE
[WIP] Update to use new IPython APIs, and prompt_toolkit fetures.

### PR DESCRIPTION
**Pull request by Carreau**
Rely on a few things not yet in master of upstream projects:

Support ZerwidthEscape Sequences:
https://github.com/jonathanslenders/python-prompt-toolkit/pull/299

IPython prompts refactor:
https://github.com/ipython/ipython/pull/9471

Store last Execution status.
https://github.com/ipython/ipython/pull/9519

### CODE REVIEW

**Comment by Carreau** [comment]
Needs https://github.com/ipython/ipython/pull/9521 as well.

**Comment by Carreau** [comment]
Well test pass, but coverage in unhappy as it does not test the codepath for IPython master.

**Comment by asmeurer** [comment]
So this works in both the current version and the master version?

**Comment by asmeurer** [comment]
I guess this shouldn't be merged until the upstream PRs are merged. It would be good to add ipython nightly (and, if it's relevant, pt nightly) to the Travis file.

**Comment by Carreau** [comment]
> So this works in both the current version and the master version?
> 
> I guess this shouldn't be merged until the upstream PRs are merged. It would be good to add ipython nightly (and, if it's relevant, pt nightly) to the Travis file.

Yes, and yes, though master will be tricky to test, as when you are not in a TTY, PTK is not used so the extension just won't do a thing.

We'll have to bypass starting IPython in a subshell, enable the extension and ask IPython for it's prompt token manually. 

THe other weird thing is that setting BEFORE_OUTPUT does not work correctly is set on the output, it has to be glue with AFTER_OUTPUT, and printed just before the output prompt, and I was not able to figure that out.

**Comment by asmeurer** [comment]
I believe the extension already outputs `BEFORE_OUTPUT` before the "Out" prompt if that's what you mean. It's a little annoying, but not a regression.

**Comment by asmeurer** [comment]
Can we mock whatever IPython's isatty check is? 

My IPython tests are about as dumb as possible, by the way. If you see a smarter way to do it, let me know.

**Comment by Carreau** [comment]
> Can we mock whatever IPython's isatty check is?

Well yes, and unfortunately no. Faking it is un necesassry: `--no-simple-prompt` does the trick, 
but it will make IPython crash if stdout is a pipe.

**Comment by asmeurer** [comment]
I think either https://docs.python.org/3.5/library/pty.html or the `script` command can help us test this.

**Comment by asmeurer** [comment]
I have a small fix for this at https://github.com/Carreau/iterm2-tools/pull/1

**Comment by asmeurer** [comment]
`ptyprocess` seems to be the ticket. Just need to figure out how to use it.

**Comment by asmeurer** [comment]
Or `pexpect`. I think a problem is that with either one, you need to read all output before any input, or else the text that is read (which is basically just the text that would be shown in a terminal) will include typeahead. It would be nice if IPython or prompt_toolkit provided a more direct way to do the testing here.

**Comment by Carreau** [comment]
This is going stale, closing. Thanks !

**Comment by asmeurer** [comment]
I do want to finish this eventually. It isn't really going stale because no other changes are being made to this repo. If you want you can click the "allow edits from collaborators" box so that I can just push to your branch if/when I mess with this. 

I honestly should just give up on testing IPython 5 and just merge this.

**Comment by Carreau** [comment]
Sorry for whatever reason I did not get your comment by mail (though I'm subscribed). Box checked. 
I might get back to that at a later point (and prompt toolkit has now better feature to customize key binding for IPython).

**Comment by asmeurer** [comment]
I did some more playing around with pexpect on the plane, but I can't get it to run through the whole session.  If someone wants this feature for iPython 5, let me know and I can fast track this (i.e., skip testing it). Otherwise, it will just have to wait until I get some more time to figure it out, or until someone else looks at it.

**Comment by asmeurer** [comment]
OK, I've given up trying to test this. I'm not really using IPython any more, so someone will have to let me know if it breaks. 

I pushed up a fix (BEFORE_OUTPUT was being used incorrectly, you need to use a `pre_execute` hook). I tested this manually and it seems to work.

**Pull request merged**
